#server:
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      maxFileSize: 20MB         #파일 한 개당 최대 사이즈
      maxRequestSize: 100MB     #요청당 최대 파일 크기
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

#상품 이미지 업로드 경로
itemImgLocation: /Users/selny/shop/item
#리소스 업로드 경로
uploadPath: file:///Users/selny/shop
